### ISSUE TITLE
 same-origin restrictions  ?

### ISSUE THREAD

**Issue by propertynoticed** [cburgmer/csscritic#61] opened 2015-04-22 09:54 UTC
How to resolve  same-origin restrictions on windows as there is no "ln" command.
Thanks in advance 
Kunal

**Comment by cburgmer** [comment] 2015-04-22 12:16
I was under the impression that newer Windows versions do support a similar concept. However it's been a while since my last Windows exposure.

On my current project the test cases / style guide is served through a server and so is the CSS Critic runner.

For now can you run a local webserver? Python for example has something simple.

Also, can you make sure that it's not just the RegressionRunner not being in the top level folder?

**Comment by cburgmer** [comment] 2015-04-22 18:21
According to http://www.windows7home.net/how-to-create-symbolic-link-in-windows-7/ and other sources this is doable, albeit not obvious.

**Comment by propertynoticed** [comment] 2015-04-23 04:19
thanks for your help. My non-angular versions are working fine. The problem is with the angular versions. I will try to work on it today. 

Thanks again
KD

**Comment by cburgmer** [comment] 2016-01-09 03:58
Closing this issue for now as it seems there's nothing more to do. Please re-open if needed!

**Closed by cburgmer** 2016-01-09 03:58 UTC
